# Generated by Django 4.1.3 on 2022-12-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_state_alter_customer_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Vung Tau', 'Vũng Tàu'), ('Ho Chi Minh', 'Hồ Chí Minh'), ('Ha Noi', 'Hà Nội')], max_length=100, null=True),
        ),
    ]
